name: Verify Metadata

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: "18"

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@20576b4b9ed46d41e2d45a2256e5e2316dde6834 # v43
        with:
          files: |
            resources
            metadata.json

      - name: Build and verify
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm run build
          npm run generateMetadata

      - name: Check for any drift via git diff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git diff --no-ext-diff --exit-code metadata.json
